web/src/main/resources/static/css/customStyles.css, web/src/main/resources/templates/methods.html
Whoops, closed PR 3 too soon.  Creating another to get the CSS changes into master
=> Externalized all css

data-model/src/main/java/org/pdxfinder/dao/ModelCreation.java, data-model/src/main/java/org/pdxfinder/dao/Patient.java, data-model/src/main/java/org/pdxfinder/dao/PatientSnapshot.java, data-model/src/main/java/org/pdxfinder/dao/Sample.java, data-model/src/main/java/org/pdxfinder/dao/Specimen.java, data-model/src/main/java/org/pdxfinder/dao/Treatment.java, data-model/src/main/java/org/pdxfinder/repositories/ModelCreationRepository.java, data-model/src/main/java/org/pdxfinder/repositories/SampleRepository.java, data-model/src/main/java/org/pdxfinder/repositories/SpecimenRepository.java, data-model/src/test/java/org/pdxfinder/integration/ModelIntegrationTest.java, data-model/src/test/java/org/pdxfinder/integration/PatientSampleIntegrationTest.java, data-model/src/test/java/org/pdxfinder/repositories/SampleRepositoryTest.java, data-services/src/main/java/org/pdxfinder/services/SearchService.java, indexer/src/main/java/org/pdxfinder/commands/LinkSamplesToDOTerms.java, indexer/src/main/java/org/pdxfinder/commands/LoadHCI.java, indexer/src/main/java/org/pdxfinder/commands/LoadIRCCData.java, indexer/src/main/java/org/pdxfinder/commands/LoadJAXData.java, indexer/src/main/java/org/pdxfinder/commands/LoadMDAnderson.java, indexer/src/main/java/org/pdxfinder/commands/LoadPDMRData.java, indexer/src/main/java/org/pdxfinder/commands/LoadWISTAR.java, indexer/src/main/java/org/pdxfinder/commands/LoadWUSTL.java, indexer/src/main/java/org/pdxfinder/commands/ValidateIRCCData.java, indexer/src/main/java/org/pdxfinder/utilities/LoaderUtils.java
=> Refactor data model

data-model/src/main/java/org/pdxfinder/dao/ValidationTechniques.java, data-services/src/main/java/org/pdxfinder/services/SearchService.java, data-services/src/main/java/org/pdxfinder/services/ds/ModelForQuery.java, data-services/src/main/java/org/pdxfinder/services/ds/ModelForQueryExport.java, indexer/src/main/java/org/pdxfinder/commands/LoadHCI.java, indexer/src/main/java/org/pdxfinder/commands/LoadWUSTL.java, web/src/main/java/org/pdxfinder/web/controllers/DetailsPageController.java, web/src/main/java/org/pdxfinder/web/controllers/SearchController.java, web/src/main/resources/templates/search.html
Merge in latest changes from dev to beta
- Fix display issues with QA
- Fix IE display issues
- Fix HCI loader
=> Merge dev to beta v2.0.3-beta

data-model/src/main/java/org/pdxfinder/dao/TreatmentComponent.java, data-services/src/main/java/org/pdxfinder/services/DataImportService.java, data-services/src/main/java/org/pdxfinder/services/DetailsService.java, data-services/src/main/java/org/pdxfinder/services/SearchService.java, data-services/src/main/java/org/pdxfinder/services/ds/Standardizer.java, indexer/src/main/resources/application.properties, web/src/main/resources/static/js/banner-gdpr.js, web/src/main/resources/static/js/pdxFinder.js, web/src/main/resources/templates/details.html, web/src/main/resources/templates/search.html
Add frontend support for drugsearch
=> Drug search

data-services/src/main/java/org/pdxfinder/services/SearchService.java, data-services/src/main/java/org/pdxfinder/services/ds/ModelForQuery.java, data-services/src/main/java/org/pdxfinder/services/ds/SearchDS.java, data-services/src/main/java/org/pdxfinder/services/dto/DrugSummaryDTO.java, data-services/src/main/java/org/pdxfinder/services/dto/WebSearchDTO.java, web/src/main/resources/templates/search.html
Update results table with drug names and responses
=> Update result table with drug names and responses

data-services/src/main/java/org/pdxfinder/services/ds/Standardizer.java
=> Add new response type

data-services/src/main/java/org/pdxfinder/services/DrugService.java
Add missing drug combinations to suggestions
=> Include drug combinations to suggestions

data-model/src/main/java/org/pdxfinder/dao/CurrentTreatment.java, data-model/src/main/java/org/pdxfinder/dao/TreatmentProtocol.java, data-model/src/main/java/org/pdxfinder/repositories/CurrentTreatmentRepository.java, data-model/src/main/java/org/pdxfinder/repositories/SampleRepository.java, data-services/src/main/java/org/pdxfinder/services/DataImportService.java, indexer/src/main/java/org/pdxfinder/commands/LoadPDMRData.java, indexer/src/main/resources/application.properties
=> Model changes

indexer/src/main/java/org/pdxfinder/commands/dataloaders/LoadHCI.java, indexer/src/main/java/org/pdxfinder/commands/dataloaders/LoadIRCC.java, indexer/src/main/java/org/pdxfinder/commands/dataloaders/LoadJAXData.java, indexer/src/main/java/org/pdxfinder/commands/dataloaders/LoadMDAnderson.java, indexer/src/main/java/org/pdxfinder/commands/dataloaders/LoadPDMRData.java, indexer/src/main/java/org/pdxfinder/commands/dataloaders/LoadWUSTL.java, indexer/src/main/java/org/pdxfinder/commands/dataloaders/LoaderBase.java, indexer/src/test/java/org.pdxfinder/commands/dataloaders/LoaderBaseTest.java
Adds functionality detailed in PDXI-621
=> Extend BaseLoader to set access modality groups for models

indexer/src/main/java/org/pdxfinder/mapping/ExportMappings.java
This includes a list of data providers to filter by, to produce a streamlined mapping file for EuroPDX.
=> Format export mappings for EuroPDX

data-model/src/main/java/org/pdxfinder/graph/repositories/PatientRepository.java, data-services/src/main/java/org/pdxfinder/services/PatientService.java
=> Fetch the harmonised treatment name for patient page

.travis.yml
=> Add static code analysis to CI

data-model/src/main/java/org/pdxfinder/graph/dao/Platform.java, data-model/src/main/java/org/pdxfinder/graph/repositories/PlatformRepository.java, data-services/src/main/java/org/pdxfinder/services/DataImportService.java, indexer/src/main/java/org/pdxfinder/dataloaders/LoadHCI.java, indexer/src/main/java/org/pdxfinder/dataloaders/LoadIRCC.java, indexer/src/main/java/org/pdxfinder/dataloaders/LoadJAXData.java, indexer/src/main/java/org/pdxfinder/dataloaders/UniversalLoader.java, indexer/src/main/java/org/pdxfinder/dataloaders/UniversalLoaderOmic.java
Add platform type to the data model to allow the same platform name to be used across different molchar types.
=> Platform update

indexer/src/main/java/org/pdxfinder/dataexport/UniversalDataExporter.java, indexer/src/main/java/org/pdxfinder/utils/ExportDataToTemplate.java, indexer/src/test/java/org/pdxfinder/dataexport/DataExportTest.java
Added tests to meet merge requirements.
Updated DownDog to export with the updated template column "ethnicity Assessment". Also improved the exported datas file structure to cut down on manual data format time.
=> Down dog added column update

indexer/src/main/java/org/pdxfinder/dataexport/UniversalDataExporter.java, indexer/src/test/java/org/pdxfinder/dataexport/DataExportTest.java
Added single column to X-dog when it writes to the Sample Platform sheet to accommodate the data correctly. Adjusted test for the added space.
=> Xdog sampe platform adj

data-services/src/main/java/org/pdxfinder/services/DetailsService.java, data-services/src/main/java/org/pdxfinder/services/dto/europepmc/Result.java
Because
*The front end was hanging on NullPointerExceptions
Added a null check in getAuthorString that will return a blank string if the value is null.  Added a null check to setRawDataLabelAndLink to return a blank string if RawDataLabel value is null.
=> Added two null checks to prevent NullPointerExceptions.

admin/src/main/java/org/pdxfinder/controllers/AjaxController.java, data-services/src/main/java/org/pdxfinder/services/MappingService.java, data-services/src/main/java/org/pdxfinder/services/OmicTransformationService.java, data-services/src/main/java/org/pdxfinder/services/UtilityService.java, data-services/src/test/java/org/pdxfinder/services/MappingServiceTest.java, indexer/src/main/java/org/pdxfinder/dataexport/ExporterTemplates.java, indexer/src/main/java/org/pdxfinder/dataexport/UniversalDataWriterServices.java, indexer/src/main/java/org/pdxfinder/dataloaders/updog/domainobjectcreation/DomainObjectCreator.java, indexer/src/main/java/org/pdxfinder/utils/CbpTransformer.java, indexer/src/main/resources/application.properties, indexer/src/test/java/org/pdxfinder/dataexport/CbpTransformerTests.java
Because:
HGNC markers did complete Entrez mappings
Changed code to parse "detailed" json that includes HGNC symbols. THis is collected from
cbioportal.ca using the "detailed" parameter on the swagger API. Other changes are included
to clean up the cbioportal exporter for shifted templates and incorrect file structure.
The OmicTranformationCode may be deprecated, but I would like to leave it until I run the rest of the PMLB.
=> Made changes to parse HGNC symbol from Detail JSON.

web/src/main/resources/templates/details.html
=> Fix broken rawDataLabel by updating Thymeleaf

indexer/src/main/java/org/pdxfinder/dataloaders/updog/tablevalidation/PdxValidationRuleset.java, indexer/src/main/java/org/pdxfinder/dataloaders/updog/tablevalidation/TableSetSpecification.java, indexer/src/main/java/org/pdxfinder/dataloaders/updog/tablevalidation/Validator.java, indexer/src/main/java/org/pdxfinder/dataloaders/updog/tablevalidation/ValueRestrictions.java, indexer/src/main/java/org/pdxfinder/dataloaders/updog/tablevalidation/error/IllegalValueError.java, indexer/src/main/java/org/pdxfinder/dataloaders/updog/tablevalidation/error/IllegalValueErrorCreator.java, indexer/src/test/java/org/pdxfinder/dataloaders/updog/tablevalidation/ValidationRestrictionTests.java, indexer/src/test/java/org/pdxfinder/dataloaders/updog/tablevalidation/error/IllegalValueErrorCreatorTest.java, indexer/src/test/java/org/pdxfinder/dataloaders/updog/tablevalidation/error/IllegalValueErrorCreatorTests.java, indexer/src/test/java/org/pdxfinder/dataloaders/updog/tablevalidation/error/IllegalValueErrorTest.java
Added charSetRestriction functionality to validator
=> Char set restrictions

data-services/src/main/java/org/pdxfinder/services/DetailsService.java, web/src/main/resources/static/css/customStyles.css, web/src/main/resources/templates/details.html
* Add tooltip to the cell where host strain name is displayed with the host strain nomenclature (symbol)
* The value of host strain name will take the value of host strain nomenclature if host strain name  is Not Specified
=> Display official strain nomenclature

data-services/pom.xml, indexer/pom.xml, indexer/src/main/java/org/pdxfinder/commandline/FinderLoader.java, indexer/src/main/java/org/pdxfinder/dataloaders/updog/Reader.java, indexer/src/main/java/org/pdxfinder/dataloaders/updog/TableUtilities.java, web/pom.xml
Updated data-model from 1.0.0-SNAPSHOT to 2.0.0
=> Data model2.0.0

web/src/main/resources/static/css/customStyles.css
- Add "uppercase" css rule to customStyles.css to uppercase text. Example:   <td class="uppercase" th:text="${model.sampleOriginTissue}">origin tissue</td>
=> Front-end casing

data-services/pom.xml, indexer/pom.xml, web/pom.xml
=> Use updated data model version dependency

web/src/main/resources/static/css/customStyles.css, web/src/main/resources/templates/details.html, web/src/main/resources/templates/search.html
- Change css rule to capitalise values according to indications in https://app.zenhub.com/workspaces/pdxfinder-board-5f0f036188f27e0014a7bdfc/issues/pdxfinder/pdxfinder/449.
=> Frontend casing

indexer/src/main/java/org/pdxfinder/dataloaders/updog/TableSetCleaner.java
Mark 'raw_data_file' exempt from lower casing rules. Fix spelling typo in variable name.
Reference: #679
=> Raw data file casing exception

web/src/main/resources/static/css/customStyles.css
- Changing request in a font in customStyles.css from http to https to avoid error: "This request has been blocked; the content must be served over HTTPS."
=> Fix tumour type filter
